upstream scaling-service {
    # Nginx sẽ tự động phân giải tất cả các IP của service 'scaling-service' trong Docker Network
    server scaling-service:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://scaling-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
